#springboot服务相关配置
server:
  ## 服务http端口号
  port: 8080
spring:
  redis:
    database: 0
    host: node4
    port: 6379

  datasource:
    master:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://node4:3306/easy_collect
      username: root
      password: root
    slave:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://node4:3306/test
      username: root
      password: root
  jpa:
    hibernate:
    #配置自动建表：update:没有表新建     ，有表更新操作,控制台显示建表语句
     ddl-auto: update
    show-sql: true